name: Automated Static Multi-Arch Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-static:
    uses: ./.github/workflows/shared-static-multi-arch-build.yml
